
const { Client } = require('pg');

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
    console.error('DATABASE_URL is missing');
    process.exit(1);
}

const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false }
});

async function setup() {
    try {
        await client.connect();
        console.log('Connected to Database');

        // Create News Table
        await client.query(`
            CREATE TABLE IF NOT EXISTS news_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                image_url TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                created_by TEXT
            );
        `);
        console.log('✅ news_items table created/verified');

        // Create User Verification Table
        await client.query(`
            CREATE TABLE IF NOT EXISTS user_verifications (
                user_code TEXT PRIMARY KEY,
                is_verified BOOLEAN DEFAULT FALSE,
                drive_connected BOOLEAN DEFAULT FALSE,
                profile_image_url TEXT,
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
        `);
        console.log('✅ user_verifications table created/verified');

        // Enable RLS (Security Best Practice)
        await client.query(`ALTER TABLE news_items ENABLE ROW LEVEL SECURITY;`);
        await client.query(`ALTER TABLE user_verifications ENABLE ROW LEVEL SECURITY;`);

        // Create Policies (Simplified for Service Role usage)
        // Check if policy exists before creating to avoid error
        const createPolicy = async (tableName, policyName, definition) => {
            try {
                // This is a bit complex in raw SQL to check conditionally, 
                // easier to just try drop then create or just ignore error
                await client.query(`DROP POLICY IF EXISTS "${policyName}" ON ${tableName};`);
                await client.query(`CREATE POLICY "${policyName}" ON ${tableName} ${definition};`);
                console.log(`✅ Policy ${policyName} on ${tableName} created`);
            } catch (e) {
                console.warn(`⚠️ Policy creation warning for ${tableName}:`, e.message);
            }
        };

        // Allow Public Read for News
        await createPolicy('news_items', 'Public Read News', 'FOR SELECT USING (true)');

        // Allow Service Role (All permissions) - Implicit by default for service_role but good to be explicit/aware
        // Actually RLS is bypassed by service_role key usually.

    } catch (err) {
        console.error('Setup Error:', err);
    } finally {
        await client.end();
    }
}

setup();
